### ISSUE TITLE
Sug: Pouvoir créer un bin depuis le Terminal Intégré et l'Explorateur de fichier

### ISSUE THREAD

**Issue by fusetim** [readthedocs-fr/bin-client-vscode#2]
L'extension fonctionne parfaitement avec les fichiers ouverts dans l'éditeur, toutefois l'option pour créer un nouveau snippet n'apparait pas dans le terminal intégré ni depuis l'explorateur de fichier.

Je comprendrais que l'accès depuis l'explorateur de fichier intégré n'est pas forcément nécessaire puisqu'il est facile d'ouvrir ces fichiers dans l'éditeur. Toutefois, j'apprécierai l'utiliser depuis le terminal intégré, car le code s'accompagne bien souvent d'exécution dans une console, notamment pour le debug.
Pouvoir créer un bin depuis le terminal intégré permettrai donc d'améliorer grandement l'UX de l'extension.

J'ai repéré que l'extension était accessible dans :
- l'onglet Output
- l'éditeur de code

J'ai repéré que l'extension n'était pas accessible dans :
- l'onglet Explorer (explorateur de fichier)
- l'onglet Terminal
- l'onglet Debug Output

![image](https://user-images.githubusercontent.com/62183512/109816185-bdd41780-7c30-11eb-881d-250b99a2f2a0.png)
![image](https://user-images.githubusercontent.com/62183512/109816262-d3e1d800-7c30-11eb-8bc6-1ef248587bdd.png)
![image](https://user-images.githubusercontent.com/62183512/109816325-e4924e00-7c30-11eb-8e47-6e30625dcdc8.png)
![image](https://user-images.githubusercontent.com/62183512/109816372-f3790080-7c30-11eb-9c1f-3c2f586d6817.png)

**Comment by Mesteery** [comment]
Très bonne idée !

Quel serait le langage par défaut, `txt` ?
Créer un bin serait seulement possible à partir d'une sélection ou aussi pour tout le contenu du Terminal/Debug Output ?

**Comment by fusetim** [comment]
Dans un premier temps à partir d'une sélection me semble être le plus essentiel, mais on peut imaginer que de temps en temps l'utilisateur aura besoin de copier l'intégralité du Terminal/Debug. 
Sinon `txt` me semble approprié comme valeur par défaut

**Comment by Mesteery** [comment]
> l'onglet Explorer (explorateur de fichier)

C'est fait.

> l'onglet Terminal

Malheureusement, l'API de VSCode ne donne pas beaucoup de contrôle sur le terminal (pas la possibilité d'obtenir son contenu ni d'obtenir une sélection, de ce que j'ai trouvé)

> l'onglet Debug Output

Same, je n'ai pas trouvé de moyen fonctionnel.
